modul02/domaci08/zad01/Cars/Cars/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Cars.Models
{
    public class Car
    {
        public int Id { get; set; }
        [Required]
        [StringLength(40, MinimumLength = 2)]
        public string Brand { get; set; }
        [Required]
        [StringLength(40, MinimumLength = 1)]
        public string Model { get; set; }
        [Required]
        [Range(1900, 2019, ErrorMessage ="{0} must be between 1900 and 2019")]
        public int Year { get; set; }
        [Required]
        [StringLength(40, MinimumLength = 3)]
        public string Color { get; set; }
        [Range(1, 10000, ErrorMessage = "{0} must be between 1 and 10000")]
        public int Displacement { get; set; }
        public Engine Engine { get; set; }
    }
}

modul02/domaci08/zad01/Cars/Cars/Models/Engine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Cars.Models
{
    public class Engine
    {
        public int Id { get; set; }
        [Required]
        [StringLength(40, MinimumLength = 1)]
        [Display(Name = "Engine Type")]
        public string Name { get; set; }
    }
}

modul02/domaci08/zad01/Cars/Cars/ViewModels/CarEngineViewModel.cs
using Cars.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cars.ViewModels
{
    public class CarEngineViewModel
    {
        public Car Car { get; set; }
        public List<Engine> Engines { get; set; }
    }
}

modul02/domaci08/zad01/Cars/Cars/Controllers/CarController.cs
using Cars.Models;
using Cars.Repository;
using Cars.Repository.Interfaces;
using Cars.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cars.Controllers
{
    public class CarController : Controller
    {
        private ICarRepository carRepo = new CarRepo();
        private IEngineRepository engineRepo = new EngineRepo();
        // GET: Car
        public ActionResult Index()
        {
            var cars = carRepo.GetAll();
            return View(cars);
        }

        public ActionResult Create()
        {
            CarEngineViewModel carEngines = new CarEngineViewModel();
            carEngines.Engines = engineRepo.GetAll().ToList();

            return View(carEngines);
        }

        [HttpPost]
        public ActionResult Create(Car car)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(car);
            //}
            if (carRepo.Create(car))
            {
                return RedirectToAction("Index");
            }

            return View("Error");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                carRepo.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        public ActionResult Edit(int id)
        {
            CarEngineViewModel carEngines = new CarEngineViewModel();
            carEngines.Engines = engineRepo.GetAll().ToList();
            carEngines.Car = carRepo.GetById(id);

            return View(carEngines);
        }

        [HttpPost]
        public ActionResult Edit(int id, Car car)
        {
            try
            {
                Engine engine = new Engine() { Id = id };
                car.Engine = engine;

                carRepo.Update(car);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

modul02/domaci08/zad01/Cars/Cars/Controllers/EngineController.cs
using Cars.Models;
using Cars.Repository;
using Cars.Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cars.Controllers
{
    public class EngineController : Controller
    {
        private IEngineRepository engineRepo = new EngineRepo();
        // GET: Engine
        public ActionResult Index()
        {
            var engines = engineRepo.GetAll();

            return View(engines);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Engine engine)
        {
            if (!ModelState.IsValid)
            {
                return View(engine);
            }
            if (engineRepo.Create(engine))
            {
                return RedirectToAction("Index");
            }

            return View("Error");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                engineRepo.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        public ActionResult Edit(int id)
        {
            Engine engine = new Engine();
            engine = engineRepo.GetById(id);

            return View(engine);
        }

        [HttpPost]
        public ActionResult Edit(int id, Engine engine)
        {
            try
            {
                engineRepo.Update(engine);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

modul02/domaci08/zad01/Cars/Cars/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cars.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

modul02/domaci08/zad01/Cars/Cars/Views/Car/Create.cshtml
@model Cars.ViewModels.CarEngineViewModel

@{
    ViewBag.Title = "Add Car";
}

<h2>Add a Car</h2>


@using (Html.BeginForm("Create", "Car", FormMethod.Post, new {onsubmit = "return isValid(this)"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Car.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Car.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Car.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Car.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Car.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Car.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Car.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Car.Year, null, "Car.Year", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Car.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Car.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Car.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Car.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Car.Displacement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Car.Displacement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Car.Displacement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.DropDownListFor(model => model.Car.Engine.Id,
                                                 new SelectList(@Model.Engines, "Id", "Name"),
                                                 "Select Engine Type")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function isValid(form) {
            alert(form["Car.Year"].value);
            vrednost = form["Car.Year"].value;
            if (isNaN(vrednost)) {
                alert("You didn't input appropriate Year format");
                form["Car.Year"].style.borderColor = "red";
                return false;
            } else if (vrednost >= 1900 && vrednost <= 2018) {
                return true;
            } else {
                alert("You didn't input a Year between 1900 and 2019");
                form["Car.Year"].style.borderColor = "red";
                return false;
            }
        }
    </script>
}

modul02/domaci08/zad01/Cars/Cars/Views/Car/Edit.cshtml
@model Cars.ViewModels.CarEngineViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Car.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Car.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Car.Brand, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Car.Brand, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Car.Model, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Car.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Car.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Car.Year, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Car.Year, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Car.Year, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Car.Color, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Car.Color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Car.Color, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Car.Displacement, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Car.Displacement, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Car.Displacement, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Engines, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select name="id">
                @foreach (var e in Model.Engines)
                {
                    if (e.Id == Model.Car.Engine.Id)
                    {
                        <option selected value="@e.Id">@e.Name</option>
                    }
                    else
                    {
                        <option value="@e.Id">@e.Name</option>
                    }
                }
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

modul02/domaci08/zad01/Cars/Cars/Views/Car/Index.cshtml
@model IEnumerable<Cars.Models.Car>

@{
    ViewBag.Title = "Engine Index";
}

<h2>Car Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Displacement)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Engine.Name)
        </th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Year)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Displacement)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Engine.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id })
        </td>
        <td>
            <form action="/car/delete" method="post">
                <input type="hidden" name="id" value="@item.Id" />
                <input type="submit" value="Delete" />
            </form>
        </td>
    </tr>
}

</table>